<?php

$title = 'registration';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('user', array('action' => 'registration')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('firstname'));
echo "<br>";
echo $this->formRow($form->get('lastname'));
echo "<br>";
echo $this->formRow($form->get('username'));
echo "<br>";
echo $this->formRow($form->get('password'));
echo "<br>";
echo $this->formRow($form->get('contact'));
echo "<br>";
echo "<strong>Gender</strong>";
echo $this->formRow($form->get('gender'));
echo "<br>";
echo $this->formRow($form->get('submit'));

/*
 * For rendering form in a single statement
 * ---------------------------------------
 * echo $this->formCollection($form);
 *
 */


echo $this->form()->closeTag();
