<!-- Filename: /module/Blog/view/blog/list/index.phtml -->
 <h1>Blog Posts</h1>
 <p>
 <?php 
   if(count($this->posts) > 0){
       echo "Total Posts: ".count($this->posts)."<br>";
   }
 ?>
<a href="<?php echo $this->url('blog/add'); ?>">Post Something From Here</a>
 <?php foreach ($this->posts as $post){ ?>
 <div id = 'blogPost'>
     <div id ='headAndButton' >
     <h2 id="post<?= $post->getId() ?>"><?= $post->getTitle() ?></h2>
     
     </div>
     <p id ='para<?php echo $post->getId(); ?>' onclick = 'convertToEditable("<?php echo $post->getId(); ?>")'>
         <?= $post->getText() ?>
     </p>
     <div id = 'textareadiv'>
     <textarea class = 'postTextAreas' id = 'paraTextArea<?php echo $post->getId(); ?>'><?= $post->getText() ?></textarea>
     </div>
     <a href="<?php echo $this->url('blog/edit', array('id' => $post->getId()), true); ?>">Edit</a>
     <a href="<?php echo $this->url('blog/delete', array('id' => $post->getId()), true); ?>">Delete</a>
     
 </div>
 <?php } ?>
