
<?php

$title = 'Add new album';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    
    <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden=
		"true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add Album</h4>
      </div>
      <div class="modal-body">
            
<?php
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();
echo "<div class = 'addContainer'>";
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo "<div class = 'editCell'>".$this->formRow($form->get('title'))."</div>";;
echo "<div class = 'editCell'>".$this->formRow($form->get('artist'))."</div>";;
echo "<div class = 'editCell'>".$this->formSubmit($form->get('submit'))."</div>";;
echo "</div>";
/*
 * For rendering form in a single statement
 * ---------------------------------------
 * echo $this->formCollection($form);
 *
 */


echo $this->form()->closeTag();
?>
      </div>
    </div>
  </div>
    
    
    
    
    
    

