<?php
$title = 'My albums';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action' => 'add')); ?>" > Add new Album</a>
</p>
<p>
    <button onclick = 'addNewAlbum()'  data-toggle="modal"  
            data-target="#formDiv">add new album using ajax</button>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) { ?>
        <tr>
            <td><?php echo $this->escapehtml($album->title); ?></td>
            <td><?php echo $this->escapehtml($album->artist); ?></td>
            <td>
                <a href="<?php echo $this->url('album', array('action' => 'edit', 'id' => $album->id));
        ?>">Edit</a>
                <a href="<?php echo $this->url('album', array('action' => 'delete', 'id' => $album->id));
        ?>">Delete</a>
            </td>
    <?php } ?>        				
</table>

<div class="modal fade" id="formDiv" tabindex="-1" role="dialog" 
     aria-labelledby="myModalLabel" aria-hidden="true">

</div>